---
all:
  hosts:
    # sonar-01:
    #   ansible_host: 51.250.22.212
    nexus-01:
      ansible_host: 51.250.16.179
  children:
    # sonarqube:
    #   hosts:
    #     sonar-01:
    nexus:
      hosts:
        nexus-01:
    # postgres:
    #   hosts:
    #     sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology